//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library_ManagementEntities : DbContext
    {
        public Library_ManagementEntities()
            : base("name=Library_ManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admintbl> Admintbls { get; set; }
        public DbSet<Booktbl> Booktbls { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Transactiontbl> Transactiontbls { get; set; }
        public DbSet<Usertbl> Usertbls { get; set; }
    }
}
