//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryMangement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booktbl
    {
        public Booktbl()
        {
            this.Transactiontbls = new HashSet<Transactiontbl>();
        }
    
        public int BookId { get; set; }
        public string BookTitle { get; set; }
        public string BookCategory { get; set; }
        public string BookAuthor { get; set; }
        public Nullable<int> BookCopies { get; set; }
        public string BookPub { get; set; }
        public string BookPubName { get; set; }
        public string BookISBN { get; set; }
        public Nullable<int> Copyright { get; set; }
        public string DateAdded { get; set; }
        public string Status { get; set; }
        public Nullable<int> AdminId { get; set; } 
    
        public virtual Admintbl Admintbl { get; set; }
        public virtual ICollection<Transactiontbl> Transactiontbls { get; set; }
    }
}
